# Generated by Django 4.0 on 2021-12-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrbot', '0002_alter_city_options_alter_work_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='interview',
            field=models.CharField(max_length=1000, null=True, verbose_name='Interview'),
        ),
    ]
