# Generated by Django 4.0 on 2021-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrbot', '0003_alter_work_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='interview',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Interview'),
        ),
    ]
