# Generated by Django 4.0 on 2021-12-16 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrbot', '0005_alter_city_address_alter_city_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)], verbose_name='Longitude'),
        ),
    ]
